#!/usr/bin/env python3

"""
A one-image registry for loading an image efficiently.

This script accepts the same arguments as `import_config`. It uses the
information to create an OCI manifest for the image and start an HTTPS server
that the image can be pulled from.
"""

import collections
import hashlib
import http
import http.server
import json
import os
import os.path
import shutil
import ssl
import sys
import tempfile
import argparse
import random
import subprocess
import threading
import time
import urllib.request
import platform

from bazel_tools.tools.python.runfiles import runfiles


# We're going to access this registry through localhost, so we don't actually
# need this to be a valid certificate - we only need to serve HTTPS. When a
# containerd snapshotter isn't configured, Docker will try plaintext HTTP too;
# when it is, it will only accept secure registries. Generated by running
# `openssl req -x509 -newkey rsa:2048 -keyout - -days 9999 -subj /CN=localhost -nodes`.
SSL_CERT = b"""
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqQUQtOivr1Lrx
ODhFpvA6FnfMjKWkAQwu29ECVNbjiF80dBII4tTyxB1XT1qk24JfNYPN4cZKYFkE
35AdXsFS3rhGqf9cAyeCu0MH7eeBPd2yQPyZOtniQDsHgNn8ICuW6iMt5L8gT28e
r94qK4MWHxyCtXT52hWmxX8QfntKqaRAOM5A5ORs90nP488vdBm1nJo3f07ZQ7gX
HmeFqavqQkFYnYEE2TUs9ByllYA7l8ohEwz83fIAHXE51LhoO3PUVBI5y1BBE8jd
llI+hG+aiatVnz9PB+E7kQMfe+5wvhj+EGLO5IC4bPeoo1EPe9asJwPlp4MxQhOQ
ybYuuENZAgMBAAECggEAGUqTvaI4FxLlaGMBHPu1EPP4fObhzlCnhih6Tn3a5DcE
aY7ahP5pQtz2PNuZbAb9wXX6K/Hfmnngj3REfNBwKIbUWg7z06/WRTnbNcjWDKFr
lwjHXV3cMxt2iWFPQIBo6UTD0BP8fmi+aZEXkC0hjn41pocdJuaKM9l/zCv11bvK
lK9RmO7Ab+QQhhstNaFgTJmeyBTWd6CM6q8OF4ObvxpWyC6ZK7sA8GEo1o20s9wE
bukW/4KLGPH/ElmjuTnqvWF1KUobdcH5COSU6hAGfSOBHs5PHKydlFOQ/pSW0qyb
AgWhLmkX2WunidPiN45Z6QeBlF1Q1YR5m1ZInrH+rwKBgQDUjCDXz9oOcGjQ9zWP
fsT6iH/zy5eWsh6NWwO33J87Y3NrIBd97dakIgfJgGSVjLXlTQ2kM+ujQMnrPd3r
NH0t+EZgA4PvVZLzIJk4UvBuSPIXCXj0u9mBlxs/nK6VvXoXYN8WTHc1OkPkPpuR
D1RV5y3eQO4RBSKf2HMaBO6NQwKBgQDND7kUvZRTTqat6AFz4PJ+JKI8AurLba60
WKEJLnw5/04OurPct1Do3A/bghrp7pc09zeSBt8R0ioe4jBcSu6k9m+UgTbHkWql
nvgi75BBtk3aXen/cvaRXmepL24UkyXGWo5d0vMh2n8/UKTdUlowQXVZ3qf7BMN0
MsXriWv1MwKBgEdMOjgqoRr22jI+utjHzYu8/i7pvI/wcA862KR0fXWOhskImtjD
T5z/TV1qlFMWQG4KyuiqAgFhWlpvBmI/2T3yaqkKhNdj/UdRSBR8vepAzfSsWMa/
vNabuag9BtN0G+B7vlncjKBuSxflaIngeonWYqyLW1CaSGMWWIYB4YPBAoGBAIxb
qLlzkeT7vsbmOKhSXmjNNmaRMJkReDVlPMSGFu2zvIAEdzwqFa1tg0UiZr2cW88b
L+Q549HU4pPFCokBmRs8ut8RGqe69x5qEzoGc90mpV9ETPhWfkK+NYHuPxDCL2b3
cN7zlwui/NofntkGl0jUZTigWKZOemI8ppAzvbtVAoGBAK3LmhwfGl2s5ZvaeNDm
100cErxuBOPeOtxM/8Mm+vyQmjOTSwaWJDP3z8x9tt4dnYwYFaxDZCijwcmVb6OM
JK5r4BQHh+bZ3oj5nvQIjGqJabpdVcHr4NRnOjghRriJOfH2f+od1imEiDyaP07X
X8V/MWu2ldnFlyT5dIlTcF74
-----END PRIVATE KEY-----
-----
-----BEGIN CERTIFICATE-----
MIIDCzCCAfOgAwIBAgIUKVv/HTCgLecVSkeSUi9CdGaCCecwDQYJKoZIhvcNAQEL
BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MCAXDTI0MTExNDE1MjEzOFoYDzIwNTIw
MzMxMTUyMTM4WjAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCqQUQtOivr1LrxODhFpvA6FnfMjKWkAQwu29ECVNbj
iF80dBII4tTyxB1XT1qk24JfNYPN4cZKYFkE35AdXsFS3rhGqf9cAyeCu0MH7eeB
Pd2yQPyZOtniQDsHgNn8ICuW6iMt5L8gT28er94qK4MWHxyCtXT52hWmxX8QfntK
qaRAOM5A5ORs90nP488vdBm1nJo3f07ZQ7gXHmeFqavqQkFYnYEE2TUs9ByllYA7
l8ohEwz83fIAHXE51LhoO3PUVBI5y1BBE8jdllI+hG+aiatVnz9PB+E7kQMfe+5w
vhj+EGLO5IC4bPeoo1EPe9asJwPlp4MxQhOQybYuuENZAgMBAAGjUzBRMB0GA1Ud
DgQWBBR4ubgDbvXfKg/CaGjm2TZKgSPOuTAfBgNVHSMEGDAWgBR4ubgDbvXfKg/C
aGjm2TZKgSPOuTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBI
yaa5gtoaCapSR164+xk2InaiI/my4HdJNnBnumvCv9dLFeKzAHi+slJbyE5GY5rk
N7XI2M7qz4hhw6X0GKsND6Hp29lfRRp7PP10jGVaBXgenR1puWyWv99ZfiJXntkA
eIZ8kxyAom0yUlxL/7AID7gDa3fgrT9Rw3LCT0sqS3V4VlzGLgRWfZqycQTa3CJS
JNnMifBmR6gRNqd67wzycseoldJ9x9S6EUshOr1VbJqJYagL/9w37Cw/09La0WSP
5PNYExjX6nGKVjNas8n1a5m4MNhdoyU17fJvfqnHNcUO0Pu7KCMQgDa+lTEfFnhY
ZMBiKR7i8UqktxOGf3Bn
-----END CERTIFICATE-----
""" # gitleaks:allow


CONFIG_MEDIA_TYPE = "application/vnd.docker.container.image.v1+json"
DIFF_MEDIA_TYPE = "application/vnd.docker.image.rootfs.diff.tar"
MANIFEST_MEDIA_TYPE = "application/vnd.docker.distribution.manifest.v2+json"


def _generate_random_string(length):
    characters = 'abcdefghijklmnopqrstuvwxyz0123456789'
    return ''.join(random.choice(characters) for _ in range(length))


class DockerV2Registry:
    def __init__(self, config_path, *layers):
        r = runfiles.Create()

        self._repo_name = "registry-%s.local" % _generate_random_string(10)
        self._registry_blobs = {}
        self._manifest = collections.OrderedDict(
            [
                ("schemaVersion", 2),
                ("mediaType", MANIFEST_MEDIA_TYPE),
                (
                    "config",
                    self._blob(
                        CONFIG_MEDIA_TYPE,
                        r.Rlocation(os.path.normpath(config_path)),
                        r.Rlocation(os.path.normpath(config_path + ".sha256")),
                    ),
                ),
                ("layers", []),
            ]
        )
        digests = layers[::2]
        tarballs = layers[1::2]
        for layer_digest_path, layer_path in zip(digests, tarballs):
            assert layer_digest_path == layer_path + ".sha256"
            blob_data = self._blob(
                DIFF_MEDIA_TYPE,
                r.Rlocation(os.path.normpath(layer_path)),
                r.Rlocation(os.path.normpath(layer_digest_path)),
            )
            self._manifest["layers"].append(blob_data)
        self._manifest_data = json.dumps(self._manifest, separators=(",", ":")).encode()
        self._manifest_digest = (
            "sha256:" + hashlib.sha256(self._manifest_data).hexdigest()
        )

    def _blob(self, media_type, blob_path, digest_path):
        with open(digest_path) as digest_file:
            digest = "sha256:" + digest_file.read()
        size = os.path.getsize(blob_path)
        self._registry_blobs[digest] = (media_type, blob_path, size)
        return {
            "mediaType": media_type,
            "digest": digest,
            "size": size,
        }

    def handler(self):
        _manifest_data = self._manifest_data
        _manifest_digest = self._manifest_digest
        _repo_name = self._repo_name
        _registry_blobs = self._registry_blobs

        class _RegistryHandler(http.server.BaseHTTPRequestHandler):
            def _is_manifest(self, path):
                return path in (
                    "/v2/%s/manifests/latest" % _repo_name,
                    "/v2/%s/manifests/%s" % (_repo_name, _manifest_digest),
                )

            def _send_blob(self, head):
                if self.path == "/v2/":
                    self.send_response(http.HTTPStatus.OK)
                    self.end_headers()
                    return

                if self._is_manifest(self.path):
                    self.send_response(http.HTTPStatus.OK)
                    self.send_header("Content-Type", MANIFEST_MEDIA_TYPE)
                    self.send_header("Content-Length", str(len(_manifest_data)))
                    self.end_headers()
                    if not head:
                        self.wfile.write(_manifest_data)
                    return

                if self.path.startswith("/v2/%s/blobs/sha256:" % _repo_name):
                    _, _, digest = self.path.rpartition("/")
                    if digest in _registry_blobs:
                        media_type, path, size = _registry_blobs[digest]
                        self.send_response(http.HTTPStatus.OK)
                        self.send_header("Content-Type", media_type)
                        self.send_header("Content-Length", str(size))
                        self.end_headers()
                        if not head:
                            with open(path, "rb") as f:
                                shutil.copyfileobj(f, self.wfile)
                        return

                self.send_error(http.HTTPStatus.NOT_FOUND)
                self.end_headers()

            def do_HEAD(self):
                self._send_blob(head=True)

            def do_GET(self):
                self._send_blob(head=False)

        return _RegistryHandler

    def image_ref(self):
        return "%s@%s" % (self._repo_name, self._manifest_digest)


ssl_context = ssl._create_unverified_context()


def is_server_ready(url):
    try:
        with urllib.request.urlopen(url, context=ssl_context) as response:
            return response.status == 200
    except:
        return False


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Load images to the docker daemon efficiently"
    )
    parser.add_argument('docker_binary', type=str, help='The path to the docker binary')
    parser.add_argument('config_path', type=str, help='The path to the image config file')
    parser.add_argument('layer_pairs', nargs='+', help='Layer digests and tarballs')
    args = parser.parse_args()

    docker_binary = args.docker_binary
    registry = DockerV2Registry(args.config_path, *args.layer_pairs)
    listen_address = "0.0.0.0" if platform.system() == "Darwin" else "127.0.0.1"
    httpd = http.server.HTTPServer(("127.0.0.1", 0), registry.handler())
    ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    with tempfile.NamedTemporaryFile() as certfile:
        certfile.write(SSL_CERT)
        certfile.flush()
        ctx.load_cert_chain(certfile=certfile.name)
    httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
    
    _, port = httpd.socket.getsockname()
    address_with_port = "localhost:%s" % port
    pullable_image = "%s/%s" % (address_with_port, registry.image_ref())
    
    def start_server():
        httpd.serve_forever()
    
    server_thread = threading.Thread(target=start_server, daemon=True)
    server_thread.start()

    tries = 5
    backoff_secs = 1
    server_running = False
    endpoint = "https://%s/v2/" % address_with_port
    for _ in range(tries):
        if is_server_ready(endpoint):
            server_running = True
            break
        else:
            time.sleep(backoff_secs)
            backoff_secs = 2 * backoff_secs

    if not server_running:
        raise Exception("Local registry is not listening on %s" % address_with_port)

    subprocess.check_call([docker_binary, "pull", pullable_image], stdout=sys.stderr, stderr=sys.stderr)
    print(pullable_image, flush=True)
