#!/usr/bin/env python3

"""
A one-image registry for loading an image efficiently.

This script accepts the same arguments as `import_config`. It uses the
information to create an OCI manifest for the image and start an HTTPS server
that the image can be pulled from.
"""

import collections
import hashlib
import http
import http.server
import json
import os
import os.path
import shutil
import ssl
import sys
import tempfile
import argparse
import random
import subprocess
import threading
import time
import urllib.request
import platform

from bazel_tools.tools.python.runfiles import runfiles


# We're going to access this registry through localhost, so we don't actually
# need this to be a valid certificate - we only need to serve HTTPS. When a
# containerd snapshotter isn't configured, Docker will try plaintext HTTP too;
# when it is, it will only accept secure registries. Generated by running
# `openssl req -x509 -newkey rsa:2048 -keyout - -days 9999 -subj /CN=localhost -addext "subjectAltName=IP:0.0.0.0" -nodes`.
SSL_CERT = b"""
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCle/4f16e8545D
Oy5GvxPG1K4wK0aW1r4H9U59U6/P3AJIwnSyJFVcZNMnh9khKaqeO/Dum6+gkh1K
p0Vkksr+KcesoNmc80k6YnqNMPXUCziNbDbPhcFWIknVTd1CZR40Vh26tLQF7TAn
N7DDGDc0NhsRBlh1MxmB4R/TIPtFCdV5PJYqpUiPjQqXW5/JMDfnxZPNPT1KJ8+p
oK2cCYLP61c9/wR/8/Km1kyMRB46pSkAouAQpvUIUyCA+ee7RDhBxAIadEO7jGd4
9ZfpF8MwLupcZGtgGIqyx2NCxLZLGh4UE737l5emItXCcd88JvHz5vY/18Rwmc81
OsE7s65nAgMBAAECggEAI/pruy+PS+5KC0rsGjyDx7hIsLdP7w58HU3ThULzF+18
36XLakmk92QCVndeGSwuaJ2embnmerIZxTfNyfpyQMUDoQANn+Zy9ssfWuAYqkPQ
RUsQNZkeeiQVSldV8g/6+6T3bLbJ5vn0/KnKd/glVGgpBVAMXlrAQnEYErZ6er05
eJh8HB2XNURqRFhZnVkMFFeTC+wisKjfhmVF1NXYvr6drpyIB05JU89x13vcZzO1
d/7JHeXteyjkCWFKE6g/OaZ4IfH5pjld/1BA1sLQlpItN3p2mVy1gB8SKNkQGtnz
Z0fE5fbgXsFkYHOjX5OV1QJ3jFsENojEW13PL8gjyQKBgQDZFmEfbA52ZMbttNN7
ebXavTCY4/WJZkouIiCCI/Uj/vB+jhowB7N2GHv3Vj0l18Tfe+CkIOh+KiRXQEg8
+2g95UMydwhZVvLwjZ/Ts+FKTfTOtP6MIkpf1jvlkGa8Ps0+R832UXBrL4/LKP2/
pEvmhBv/XWn77A96vxrXgKgDnwKBgQDDJawQUF5BcnD1Y6FSsnssenEOuD7TOAoB
cwERjM0Tn6VA/44J7tFzBd9EOYbw22U6vweMTHhJxQgSuRxT49BkOT1lAcWz98rO
bq1FYUO+TzoRIa1AtJr0nSE4ptr4/5+rbfYzpmJQe/f8Sqs9XorTFQToAtuWDptK
5EaxgskgOQKBgAOvzpxzAFfgZER7MrBBI+aAGggurufTdeUMrVKoe6xN0xXDIgy4
xMJ3rftIWqd+35gQCYOgD3K9Enrs2401k9KhRx/fR6QExwFw1ksJHgVeB49PIZeN
qYexIrlGV4hQ5LlvDL9nKKqZVy7TFmQfzS4wBi2zD2641pZ2EmWgiLnvAoGBAKAh
PISSfhV0I86oN0tVm48O1dC/TQYi+MrhpKHTCMCugnrIeLQb3JBm5CLmlZz0WqeO
81GjuhzGae57KQyJZomnEoLcpm8byLYFyXah7mWuOzatjK4IxRIuEYGcIRirIUkZ
TSpqwEfMwdurJcKQ3peAqur61VbXm4QjtwKYEBO5AoGAKFXTOn5GsVBTRNCbbO8h
4Ed8hoFv70gTx1c35x5eO9AhR7cq4o32W5wcyJFiA94EFcrjbRQNWAOiToloy+gL
hHejpKoE6Por/8PgcLMJvrJ1LnuEBjAO/XFFF/gEhMYyE9mQkFU3qa1VAWOIlo1q
+W47ImItn3o8dKXHSaFHreY=
-----END PRIVATE KEY-----
-----
-----BEGIN CERTIFICATE-----
MIIDHDCCAgSgAwIBAgIUDro+/9ssRM0CBm3+wAnSsijLBR4wDQYJKoZIhvcNAQEL
BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MCAXDTI0MTExNDE1MzIwOVoYDzIwNTIw
MzMxMTUzMjA5WjAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCle/4f16e8545DOy5GvxPG1K4wK0aW1r4H9U59U6/P
3AJIwnSyJFVcZNMnh9khKaqeO/Dum6+gkh1Kp0Vkksr+KcesoNmc80k6YnqNMPXU
CziNbDbPhcFWIknVTd1CZR40Vh26tLQF7TAnN7DDGDc0NhsRBlh1MxmB4R/TIPtF
CdV5PJYqpUiPjQqXW5/JMDfnxZPNPT1KJ8+poK2cCYLP61c9/wR/8/Km1kyMRB46
pSkAouAQpvUIUyCA+ee7RDhBxAIadEO7jGd49ZfpF8MwLupcZGtgGIqyx2NCxLZL
Gh4UE737l5emItXCcd88JvHz5vY/18Rwmc81OsE7s65nAgMBAAGjZDBiMB0GA1Ud
DgQWBBR3Gt8a6dpZyU2PUzecA+H3iNSCkTAfBgNVHSMEGDAWgBR3Gt8a6dpZyU2P
UzecA+H3iNSCkTAPBgNVHRMBAf8EBTADAQH/MA8GA1UdEQQIMAaHBAAAAAAwDQYJ
KoZIhvcNAQELBQADggEBAFcTpOrOCelcRtvMGa1NERd5YQZeyWKtMfdKmDpswDIT
ZySbPnbW+9dD00gyp6g6aStiklhMAhMddNpo29O7f6/sc5iBUaQp+y0hUV+l4EFA
baSyRqNphDJ/1kfqAVfyfOBxJZ44CjGHAu2GmpoRlIkz7yXrSWy4IlygzxBMw6Gb
jvtkqvGCYqZ2VBtHjEfrjwUUIxHArc7+BTcWfWJxYkEoUnDdKrXp3sn8TzCT+3nm
AyK1DbP7I8uKDTUpWVmVDyHZT/hlBz4cg3Pi3UTNzRsOcfzyZivJVcdaFKss0hRm
5lcRfr9BTTgM2yrUp7+YibPl/bntG/z5b+bXVUOdaW8=
-----END CERTIFICATE-----
""" # gitleaks:allow


CONFIG_MEDIA_TYPE = "application/vnd.docker.container.image.v1+json"
DIFF_MEDIA_TYPE = "application/vnd.docker.image.rootfs.diff.tar"
MANIFEST_MEDIA_TYPE = "application/vnd.docker.distribution.manifest.v2+json"


def _generate_random_string(length):
    characters = 'abcdefghijklmnopqrstuvwxyz0123456789'
    return ''.join(random.choice(characters) for _ in range(length))


class DockerV2Registry:
    def __init__(self, config_path, *layers):
        r = runfiles.Create()

        self._repo_name = "registry-%s.local" % _generate_random_string(10)
        self._registry_blobs = {}
        self._manifest = collections.OrderedDict(
            [
                ("schemaVersion", 2),
                ("mediaType", MANIFEST_MEDIA_TYPE),
                (
                    "config",
                    self._blob(
                        CONFIG_MEDIA_TYPE,
                        r.Rlocation(os.path.normpath(config_path)),
                        r.Rlocation(os.path.normpath(config_path + ".sha256")),
                    ),
                ),
                ("layers", []),
            ]
        )
        digests = layers[::2]
        tarballs = layers[1::2]
        for layer_digest_path, layer_path in zip(digests, tarballs):
            assert layer_digest_path == layer_path + ".sha256"
            blob_data = self._blob(
                DIFF_MEDIA_TYPE,
                r.Rlocation(os.path.normpath(layer_path)),
                r.Rlocation(os.path.normpath(layer_digest_path)),
            )
            self._manifest["layers"].append(blob_data)
        self._manifest_data = json.dumps(self._manifest, separators=(",", ":")).encode()
        self._manifest_digest = (
            "sha256:" + hashlib.sha256(self._manifest_data).hexdigest()
        )

    def _blob(self, media_type, blob_path, digest_path):
        with open(digest_path) as digest_file:
            digest = "sha256:" + digest_file.read()
        size = os.path.getsize(blob_path)
        self._registry_blobs[digest] = (media_type, blob_path, size)
        return {
            "mediaType": media_type,
            "digest": digest,
            "size": size,
        }

    def handler(self):
        _manifest_data = self._manifest_data
        _manifest_digest = self._manifest_digest
        _repo_name = self._repo_name
        _registry_blobs = self._registry_blobs

        class _RegistryHandler(http.server.BaseHTTPRequestHandler):
            def _is_manifest(self, path):
                return path in (
                    "/v2/%s/manifests/latest" % _repo_name,
                    "/v2/%s/manifests/%s" % (_repo_name, _manifest_digest),
                )

            def _send_blob(self, head):
                if self.path == "/v2/":
                    self.send_response(http.HTTPStatus.OK)
                    self.end_headers()
                    return

                if self._is_manifest(self.path):
                    self.send_response(http.HTTPStatus.OK)
                    self.send_header("Content-Type", MANIFEST_MEDIA_TYPE)
                    self.send_header("Content-Length", str(len(_manifest_data)))
                    self.end_headers()
                    if not head:
                        self.wfile.write(_manifest_data)
                    return

                if self.path.startswith("/v2/%s/blobs/sha256:" % _repo_name):
                    _, _, digest = self.path.rpartition("/")
                    if digest in _registry_blobs:
                        media_type, path, size = _registry_blobs[digest]
                        self.send_response(http.HTTPStatus.OK)
                        self.send_header("Content-Type", media_type)
                        self.send_header("Content-Length", str(size))
                        self.end_headers()
                        if not head:
                            with open(path, "rb") as f:
                                shutil.copyfileobj(f, self.wfile)
                        return

                self.send_error(http.HTTPStatus.NOT_FOUND)
                self.end_headers()

            def do_HEAD(self):
                self._send_blob(head=True)

            def do_GET(self):
                self._send_blob(head=False)

        return _RegistryHandler

    def image_ref(self):
        return "%s@%s" % (self._repo_name, self._manifest_digest)


ssl_context = ssl._create_unverified_context()


def is_server_ready(url):
    try:
        with urllib.request.urlopen(url, context=ssl_context) as response:
            return response.status == 200
    except:
        return False


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Load images to the docker daemon efficiently"
    )
    parser.add_argument('docker_binary', type=str, help='The path to the docker binary')
    parser.add_argument('config_path', type=str, help='The path to the image config file')
    parser.add_argument('layer_pairs', nargs='+', help='Layer digests and tarballs')
    args = parser.parse_args()

    docker_binary = args.docker_binary
    registry = DockerV2Registry(args.config_path, *args.layer_pairs)
    listen_address = "0.0.0.0" if platform.system() == "Darwin" else "127.0.0.1"
    httpd = http.server.HTTPServer(("127.0.0.1", 0), registry.handler())
    ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    with tempfile.NamedTemporaryFile() as certfile:
        certfile.write(SSL_CERT)
        certfile.flush()
        ctx.load_cert_chain(certfile=certfile.name)
    httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
    
    _, port = httpd.socket.getsockname()
    address_with_port = "localhost:%s" % port
    pullable_image = "%s/%s" % (address_with_port, registry.image_ref())
    
    def start_server():
        httpd.serve_forever()
    
    server_thread = threading.Thread(target=start_server, daemon=True)
    server_thread.start()

    tries = 5
    backoff_secs = 1
    server_running = False
    endpoint = "https://%s/v2/" % address_with_port
    for _ in range(tries):
        if is_server_ready(endpoint):
            server_running = True
            break
        else:
            time.sleep(backoff_secs)
            backoff_secs = 2 * backoff_secs

    if not server_running:
        raise Exception("Local registry is not listening on %s" % address_with_port)

    subprocess.check_call([docker_binary, "pull", pullable_image], stdout=sys.stderr, stderr=sys.stderr)
    print(pullable_image, flush=True)
